//! Node identity, byte-for-byte compatible with Python `core.py`.
//!
//! A fingerprint is the ledger's primary key for a node (with its source), so
//! the two implementations must produce the *same 16 hex chars* for the same
//! node. Workstreams/13's shadow comparison diffs exactly this set; a
//! one-character difference would report every node as "missing in the other
//! implementation".
//!
//! The compatibility surface is not the hash -- SHA-256 is SHA-256 -- but the
//! **byte string being hashed**, and that depends on three details of
//! `json.dumps` that `serde_json` does not reproduce by default:
//!
//! 1. `sort_keys=True` sorts every level, not just the top one.
//! 2. The default separators are `(', ', ': ')` -- with a space after the
//!    comma and after the colon. `serde_json::to_string` emits `{"a":1}`.
//! 3. `ensure_ascii=False` emits raw UTF-8; `serde_json` does the same, so
//!    this one already agrees.
//!
//! Get any of them wrong and every fingerprint is wrong -- which is why the
//! tests below assert against values generated by the Python implementation
//! rather than against values this code produced.

use std::collections::BTreeMap;

use serde::Serialize;
use serde_json::Value;
use sha2::{Digest, Sha256};

/// Fields `core.prepare` strips before the proxy reaches the kernel.
///
/// `dialer-proxy` is handled separately there: it survives when it names a
/// proxy that is really in the same config, because a chained node tested
/// without it is tested on a path its owner never uses.
pub const DROP_FIELDS: [&str; 3] = ["dialer-proxy", "interface-name", "routing-mark"];

/// A proxy missing any of these is dropped rather than handed to the kernel.
pub const REQUIRED: [&str; 4] = ["name", "type", "server", "port"];

/// `core.fingerprint_proxy`: 16 hex chars of `sha256` over the connection
/// parameters, with `name` and every `_`-prefixed field excluded.
///
/// Excluding `name` is the whole point: upstream lists carry duplicate names,
/// and the position-derived `#2` suffix can swap between rounds. Keying
/// convergence state on the name would let one node's failure streak be shared
/// with -- and cancelled out by -- a differently-named twin.
pub fn fingerprint_proxy(proxy: &Value) -> String {
    let material = canonical_material(proxy);
    let json = to_python_json(&material);
    hex16(&json)
}

/// `core.variant_fingerprint`: a stable identity for one *measurement* of a
/// node.
///
/// `fingerprint_proxy` ignores `dialer-proxy`, which folds a node's per-front
/// variants into one ledger row -- "any front carried it" is the verdict. The
/// same property would fold a node measured both chained and direct, so the
/// second measurement gets a derived identity rather than a decorated name:
/// the ledger asserts a fingerprint is exactly 16 hex chars.
pub fn variant_fingerprint(fp: &str, variant: &str) -> String {
    hex16(&format!("{fp}#{variant}"))
}

/// The `name`/`_`-stripped, recursively sorted copy of a proxy.
fn canonical_material(proxy: &Value) -> Value {
    let Some(map) = proxy.as_object() else {
        return proxy.clone();
    };
    let mut out = serde_json::Map::new();
    for (key, value) in map {
        if key == "name" || key.starts_with('_') {
            continue;
        }
        out.insert(key.clone(), value.clone());
    }
    sort_recursively(&Value::Object(out))
}

/// `sort_keys=True` sorts nested objects too. `serde_json`'s `preserve_order`
/// (enabled workspace-wide so generated configs diff against Python's) makes
/// `Map` an insertion-ordered `IndexMap`, so sorting has to be explicit.
fn sort_recursively(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            let mut out = serde_json::Map::new();
            for key in keys {
                out.insert(key.clone(), sort_recursively(&map[key]));
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(sort_recursively).collect()),
        other => other.clone(),
    }
}

fn hex16(text: &str) -> String {
    let digest = Sha256::digest(text.as_bytes());
    // `{:x}` on the first 8 bytes: Python slices the 64-char hex string to 16,
    // which is the same 8 bytes.
    digest[..8].iter().map(|b| format!("{b:02x}")).collect()
}

/// `json.dumps(..., sort_keys=True, ensure_ascii=False)`.
fn to_python_json(value: &Value) -> String {
    let mut buf = Vec::new();
    let mut serializer = serde_json::Serializer::with_formatter(&mut buf, PythonJson);
    value
        .serialize(&mut serializer)
        .expect("a serde_json::Value always serializes");
    String::from_utf8(buf).expect("serde_json emits UTF-8")
}

/// serde_json's default formatter is compact; Python's `json.dumps` default is
/// `separators=(', ', ': ')`. Only the two separators differ.
struct PythonJson;

impl serde_json::ser::Formatter for PythonJson {
    fn begin_array_value<W>(&mut self, writer: &mut W, first: bool) -> std::io::Result<()>
    where
        W: ?Sized + std::io::Write,
    {
        if first {
            Ok(())
        } else {
            writer.write_all(b", ")
        }
    }

    fn begin_object_key<W>(&mut self, writer: &mut W, first: bool) -> std::io::Result<()>
    where
        W: ?Sized + std::io::Write,
    {
        if first {
            Ok(())
        } else {
            writer.write_all(b", ")
        }
    }

    fn begin_object_value<W>(&mut self, writer: &mut W) -> std::io::Result<()>
    where
        W: ?Sized + std::io::Write,
    {
        writer.write_all(b": ")
    }
}

/// Compile-time proof that the canonical material is what Python hashes, for
/// debugging a mismatch without running the Python side.
pub fn canonical_json(proxy: &Value) -> String {
    to_python_json(&canonical_material(proxy))
}

/// Sorted key set of the canonical material, for diagnostics.
pub fn canonical_keys(proxy: &Value) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    if let Some(map) = canonical_material(proxy).as_object() {
        for (key, value) in map {
            out.insert(key.clone(), value.to_string());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // Every expected value below was produced by running
    // `mihomo_test.core.fingerprint_proxy` / `variant_fingerprint` on the same
    // input. Do not "fix" a failing assertion by pasting this code's output:
    // that would only prove the Rust agrees with itself.

    #[test]
    fn the_name_is_excluded_from_the_identity() {
        let a = json!({"name": "node-a", "type": "ss", "server": "1.2.3.4",
                       "port": 8388, "cipher": "aes-128-gcm", "password": "pw"});
        let b = json!({"name": "完全不同的名字", "type": "ss", "server": "1.2.3.4",
                       "port": 8388, "cipher": "aes-128-gcm", "password": "pw"});
        assert_eq!(fingerprint_proxy(&a), "6d8b3b4e1624992d");
        assert_eq!(fingerprint_proxy(&b), "6d8b3b4e1624992d");
        assert_eq!(fingerprint_proxy(&a), fingerprint_proxy(&b));
    }

    #[test]
    fn a_string_port_is_a_different_identity_from_an_int_port() {
        // 443 and "443" hash differently -- the ledger keeps them apart, and
        // `prepare`'s int coercion is what makes a node keep ONE identity
        // across rounds. Getting this backwards would silently re-key nodes.
        let proxy = json!({"name": "b", "type": "vmess", "server": "example.com",
                           "port": "443", "uuid": "1111", "network": "ws"});
        assert_eq!(fingerprint_proxy(&proxy), "de127ed14358b8d3");
    }

    #[test]
    fn dropped_fields_do_not_reach_the_identity() {
        // `dialer-proxy` and `_`-prefixed keys are stripped, so a node keeps
        // its identity whichever front it was measured through.
        let proxy = json!({"name": "c", "type": "ss", "server": "5.6.7.8", "port": 1,
                           "cipher": "x", "password": "y",
                           "dialer-proxy": "front", "_internal": {"a": 1}});
        assert_eq!(fingerprint_proxy(&proxy), "73a2280bc71d50a4");
    }

    #[test]
    fn nested_objects_are_sorted_too() {
        let proxy = json!({"name": "d", "type": "trojan", "server": "t.example",
                           "port": 443, "password": "p",
                           "ws-opts": {"path": "/z", "headers": {"Host": "h"}}});
        assert_eq!(fingerprint_proxy(&proxy), "ad7c9eac764daa23");
    }

    #[test]
    fn the_canonical_json_carries_pythons_spacing() {
        // The single most likely way to break compatibility: a compact
        // serializer produces a different byte string and therefore a
        // different hash for every node in the fleet.
        let proxy = json!({"name": "d", "type": "trojan", "server": "t.example",
                           "port": 443, "password": "p",
                           "ws-opts": {"path": "/z", "headers": {"Host": "h"}}});
        assert_eq!(
            canonical_json(&proxy),
            r#"{"password": "p", "port": 443, "server": "t.example", "type": "trojan", "ws-opts": {"headers": {"Host": "h"}, "path": "/z"}}"#
        );
    }

    #[test]
    fn a_variant_fingerprint_derives_from_the_base() {
        let fp = fingerprint_proxy(&json!({"name": "node-a", "type": "ss", "server": "1.2.3.4",
                                           "port": 8388, "cipher": "aes-128-gcm", "password": "pw"}));
        assert_eq!(variant_fingerprint(&fp, "direct"), "bcf26745ac7ffe35");
        assert_ne!(
            variant_fingerprint(&fp, "direct"),
            variant_fingerprint(&fp, "chain")
        );
    }

    #[test]
    fn identities_are_sixteen_hex_characters() {
        let fp = fingerprint_proxy(&json!({"name": "x", "type": "ss", "server": "a", "port": 1}));
        assert_eq!(fp.len(), 16);
        assert!(fp.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn a_non_object_proxy_does_not_panic() {
        // Defensive: a malformed entry must be droppable, not fatal.
        assert_eq!(fingerprint_proxy(&json!("not a proxy")).len(), 16);
        assert_eq!(fingerprint_proxy(&json!(null)).len(), 16);
    }
}
